JavaScript functions and signatures
nilete22/JavaScript-functions-challenge1 pull request #1
Opened 2023-11-14 19:20 UTC by nilete22

2023-11-19 20:13 UTC, tictools requested changes

2023-11-19 20:13 UTC, tictools commented on exercise_01/getDistanceFromThreshold.js
> +    throw new Error("Both arguments must be numbers");
We haven't still learnt how to use `throw`.
Do you know how to properly use it?
Have you tested it in your `index.js`? How are you controlling this error? 🤔

2023-11-19 20:13 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +    throw new Error("Input must be a string");
Same here regarding `throw`... 🤔

2023-11-19 20:13 UTC, tictools commented on exercise_02/index.js
> +console.log(getTotalWordsFromString(inputString));
How are you controlling thrown error here if passed argument is not a `string`?

2023-11-19 20:13 UTC, tictools commented on exercise_03/index.js
> +console.log(generateRandomNumberInRange(limit));
Same here: how do yo control error?

2023-11-19 20:13 UTC, tictools commented on exercise_04/index.js
> +console.log(isGreaterThan(10, 1));
Same here: how do yo control error?

2023-11-19 20:13 UTC, tictools commented on exercise_05/index.js
> +console.log(isAdditionGreaterThanFifty(35, 25));
Same here: how do yo control error?

2023-11-19 20:13 UTC, tictools commented on exercise_06/index.js
> +console.log(checkCollectionHasElements(collection));
Same here: how do yo control error?

2023-11-19 20:13 UTC, tictools commented on exercise_07/index.js
> +console.log(isTypeOf(stringValue, "string"));
Same here: how do yo control error?

2023-11-19 20:13 UTC, tictools commented on exercise_07/isTypeOf.js
> +function isTypeOf(value, type) {
You can simplify this logic. Avoid using `switch` if you can implement simple `if` structures.

FIX: simplify logic without `switch`

2023-11-20 18:45 UTC, MartiCobos99 requested changes
Fix the package.json file!

2023-11-20 18:45 UTC, MartiCobos99 commented on package.json
>    },
Lint and Lint:Fix are missing

2023-11-21 07:08 UTC, tictools requested changes

2023-11-21 07:08 UTC, tictools commented on .github/workflow/pipeline.yml
FIX: rename folders. Job is not executed

2023-11-22 18:36 UTC, tictools approved these changes

2023-11-26 17:09 UTC, merged